### ISSUE TITLE
Wrong window control button icons shown in the preferences window

### ISSUE THREAD

**Issue by casasfernando** [bitstower/markets#43] opened 2020-12-04 07:24 UTC
## Test case

1. Open the preferences dialog/window for the app
2. Notice the window control buttons icons are all the same and showed as "back button" icons.

App version: latest flatpak package
Distro: elementary OS 5.1.7 "Hera"
Desktop: Pantheon
GTK version (elementary OS): 3.22.30

### Actual

The window control buttons looks like in the capture below:

![Screenshot from 2020-12-04 08 13 57](https://user-images.githubusercontent.com/15861819/101133639-6a3e3780-3609-11eb-8564-56cb5d754d63.png)

### Expected

The rest of the app windows show the right window control buttons as you can see in the captures below:

![Screenshot from 2020-12-04 08 14 39](https://user-images.githubusercontent.com/15861819/101133646-6dd1be80-3609-11eb-8512-0e2c145a1bda.png)

![Screenshot from 2020-12-04 08 15 05](https://user-images.githubusercontent.com/15861819/101133653-70341880-3609-11eb-923e-f97ab51147df.png)

Thanks

**Comment by tomasz-oponowicz** [comment] 2020-12-04 11:04
Thanks! Most likely this is because of `Hdy.PreferencesWindow` (a responsive dialog template). Let's if this is still present after upgrading to the latest libhandy #38

**Comment by nekohayo** [comment] 2020-12-11 23:27
There's something weird going on in version 0.4.0 I got from flathub, too... it doesn't show the Close button at all with Adwaita, until you resize the window wider (with Super+middleclickdrag):

![Screenshot from 2020-12-11 18-26-39](https://user-images.githubusercontent.com/479401/101964158-749a9b80-3bde-11eb-8c0c-559f480a3d77.png)

**Comment by tomasz-oponowicz** [comment] 2020-12-26 13:41
Hmm... I can't reproduce it. I have two variations of the preferences dialog:

![Screenshot from 2020-12-26 14-35-57](https://user-images.githubusercontent.com/615940/103152395-cbc87080-4787-11eb-8243-d135db117084.png)
![Screenshot from 2020-12-26 14-35-45](https://user-images.githubusercontent.com/615940/103152396-ccf99d80-4787-11eb-916b-931b4a26c293.png)

Which version of flatpak do you have?

My environment:
* Flatpak 1.9.2
* Gnome 3.38.2

**Comment by casasfernando** [comment] 2020-12-26 14:03
My OS environment:

- Flatpak 1.8.3
- Pantheon desktop (elementary OS 5.1.7 Hera)

My flatpak environment:

```
$ flatpak list --app --columns=application,runtime
Application ID                              Runtime
com.bitstower.Markets                       org.gnome.Platform/x86_64/3.38
```

**Comment by nekohayo** [comment] 2021-01-05 00:39
I'm running Fedora 33 with GNOME 3.38.2 on Xorg, Flatpak 1.8.4 with Markets as "org.gnome.Platform/x86_64/3.38"

The fact that it hides the X button when the window is small, rather than hiding the search button, makes no sense to me. The window. Why is that dialog even using Hdy/LibHandy? It's not big enough to be unable to fit on any screen, including phones....

The Esc keyboard shortcut should also be bound to allow exiting that window easily (not everyone knows or can use Alt+F4)

**Comment by tomasz-oponowicz** [comment] 2021-02-22 09:50
In the meantime I upgraded to the libhandy 1.0. I think it's ok right now.

I've just tested the latest version (0.5.1) on elementaryOS 5.1 and it looks good. 
@casasfernando Please double check.

![Screenshot from 2021-02-15 12-28-53](https://user-images.githubusercontent.com/615940/108690935-36352d00-74fb-11eb-866e-f4119d455e18.png)

**Comment by casasfernando** [comment] 2021-02-22 10:14
> In the meantime I upgraded to the libhandy 1.0. I think it's ok right now.
> 
> I've just tested the latest version (0.5.1) on elementaryOS 5.1 and it looks good.
> @casasfernando Please double check.
> 
> ![Screenshot from 2021-02-15 12-28-53](https://user-images.githubusercontent.com/615940/108690935-36352d00-74fb-11eb-866e-f4119d455e18.png)

Indeed. It's fixed in 0.5.1.
@tomasz-oponowicz feel free to close to issue unless you want to address @nekohayo feedback on this same issue.
Up to you and thanks for fixing this!

**Comment by tomasz-oponowicz** [comment] 2021-02-22 10:18
I think the @nekohayo issue is also gone. Closing...

**Closed by tomasz-oponowicz** 2021-02-22 10:18 UTC
Labels: bug

**Comment by nekohayo** [comment] 2021-02-23 13:47
Yep, it works as expected now.
