### ISSUE TITLE
darkmode not working

### ISSUE THREAD

**Issue by jkotra** [bitstower/markets#16] opened 2020-08-01 09:42 UTC
## Test case

1.open app.
2. Preferences -> dark theme
3. nothing happens

### Actual

None

### Expected

Turn on dark mode / dark theme

## System

Arch Linux rolling.
flatpak version of markets v0.1.0 (https://flathub.org/apps/details/com.bitstower.Markets)

**Comment by tomasz-oponowicz** [comment] 2020-08-01 20:24
@jkotra Thanks for the bug report. What GTK theme do you use? Different than Adwaita? For example I can reproduce this when my system GTK theme is Arc.

**Comment by jkotra** [comment] 2020-08-02 05:33
I use [yaru colors](https://aur.archlinux.org/packages/yaru-colors-gtk-theme-git/)

**Comment by tomasz-oponowicz** [comment] 2020-08-04 20:53
@jkotra 

Looks like the application sets the dark mode properly. I think your theme isn't installed in a sandbox environment.

Find your theme in Flathub:

```
flatpak remote-ls --system flathub | grep org.gtk.Gtk3theme
```

The fix for this issue is to install your current Gtk theme from Flathub. For example I'm testing against the Arc theme:

```
sudo pacman -S arc-gtk-theme
flatpak install --system flathub com.bitstower.Markets 
flatpak install --system flathub org.gtk.Gtk3theme.Arc
```

More information at:
https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html

**Comment by tomasz-oponowicz** [comment] 2020-08-07 13:54
Closing. Feel free to reopen if the issue still exists.

**Closed by tomasz-oponowicz** 2020-08-07 13:54 UTC
Labels: bug
